### ISSUE TITLE
Fallo acceso UOC Notifier

### ISSUE THREAD

**Issue by cl1000** [UOC-notifier/UOC-notifier-chrome#20]
Buenos días.

Llevo varios días sin poder utilizar esta extensión. No me llegan las notificaciones, pero tampoco puedo acceder desde la propia extensión. Me salen diferentes errores según lo que quiera hacer:

Error al intentar acceder al campus:
![campus](https://user-images.githubusercontent.com/33248399/32212790-c7f4f8ee-be18-11e7-98f4-1919c8cfa0d9.jpg)

Error al intentar acceder a la agenda:
![error agenda](https://user-images.githubusercontent.com/33248399/32212815-db28f60e-be18-11e7-8332-a3ab3106ff45.jpg)

Error al intentar entrar a un aula:
![error aula](https://user-images.githubusercontent.com/33248399/32212819-df299ae2-be18-11e7-90be-f5863912ec94.jpg)

Como puedo solucionarlo?

Muchas gracias.

**Comment by crazyserver** [comment]
Hola, perdona, acabo de ver la notificación. Se te ha solucionado? Puede que necesites reiniciar la sesión. Tienes un botón rojo en las opciones para ello.

**Comment by jagedn** [comment]
cierro la issue por inactividad
