### ISSUE TITLE
La app no conecta

### ISSUE THREAD

**Issue by kossm0** [UOC-notifier/UOC-notifier-chrome#26]
Hola Pau ¿que tal?,

Oye la app ha dejado de ir... ahora no conecta :(

**Comment by jagedn** [comment]
a mi sí me va 

veo mensajes pendientes y puedo abrirlos. Tal vez fue un problema puntual. Prueba de nuevo y si va cierra la incidencia

**Comment by algar20** [comment]
Igual que a @jagedn, a mi también me conecta y me funciona correctamente.

**Comment by kossm0** [comment]
Ok, ahora estoy trabajando cuando llegue a casa mirare de actualizar el chrome y desinstalare e instalaré nuevamente a ver si me conecta. Pensé que con los cambios en el acceso de la uoc había dejado de ir

**Comment by kossm0** [comment]
Puff...el chrome no estaba actualizado, desde la propia aplicacion daba error para actualizar, lo descargue manual y lo instalé.. desinstalé e instale la extensión y nada... he tenido que borrar la carpeta de las preferencias... y FUNCIONÓ! a ver si se queda estable. Gracias por avisarme que seguía operativo
